apiVersion: 1
datasources:
  - name: "ClickHouse AOI"
    uid: ch_aoi
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      server: "http://127.0.0.1:8123"   # BẮT BUỘC: endpoint HTTP của ClickHouse
      defaultDatabase: "aoi"
      tlsSkipVerify: true
    secureJsonData:
      username: "default"
      password: "280402"
    editable: false   # provisioning ⇒ read-only là bình thường
