
minio:
  endpoint: "${MINIO_ENDPOINT:-minio:9002}"
  access_key: "${MINIO_ACCESS_KEY}"
  secret_key: "${MINIO_SECRET_KEY}"
  bucket: "aoi"
  secure: false

clickhouse:
  http_url: "${CLICKHOUSE_HTTP:-http://clickhouse:8123}"
  user: "${CLICKHOUSE_USER:-default}"
  password: "${CLICKHOUSE_PASSWORD:-}"
  database: "aoi"
